### ISSUE TITLE
Hard coded record types not showing for 50 and 52

### ISSUE THREAD

**Issue by ryanmwetzel** [moov-io/imagecashletter#113]
**What were you trying to do?**
Creating an ICL file using the "content" endpoint.

**What did you expect to see?**
Hard coded record type prior to the record for types 50 and 52.

**What did you see?**
No record type present.

**How can we reproduce the problem?**
Hard code the record types for 50 and 52 to populate in the "content" endpoint.

**Comment by adamdecaf** [comment]
Just to confirm you're calling `GET /files/{fileId}/contents` and not getting 50 / 52 as recordType values?

**Comment by ryanmwetzel** [comment]
Correct. All the others coming in correctly (haven’t test additional
addendum yet)

**Comment by adamdecaf** [comment]
@ryanmwetzel This should be fixed now after https://github.com/moov-io/imagecashletter/pull/127 was merged. Assuming you created the file from JSON.

**Comment by ryanmwetzel** [comment]
Yup.  Working as expected now.
