### ISSUE TITLE
Record Length binary not present prior to each Record 

### ISSUE THREAD

**Issue by ryanmwetzel** [moov-io/imagecashletter#114]
Each record type requires a "Record Length" in binary prior to the Record Type.  These are always 4 bytes total.  For example Record Type 01 (File Header) is 80 bytes, so the hexadecimal equivalent would be 0x00000050.  All other record types I have encountered so far are also 80.  The only Record Type that varies is 52 (Image View Detail) due to the 117 bytes of meta data and the variable length of the Image Data (52.19).  If the file size in bytes was 1334 (also field 52.18), it would be field 1134 + 117 = 0x000004E3.

**Comment by adamdecaf** [comment]
Do you know which microversion of X9 this is for?

**Comment by ryanmwetzel** [comment]
I know it’s for FIS 187 standard.

**Comment by ryanmwetzel** [comment]
Corrected with #123 and recent release.
