### ISSUE TITLE
LF or CR not accepted by validators

### ISSUE THREAD

**Issue by ryanmwetzel** [moov-io/imagecashletter#115]
**What were you trying to do?**
Validate a X9 file.

**What did you see?**
Validation fails because of LF or CR in the file.

**How can we reproduce the problem?**
Remove LF and CR from the "content" endpoint

**Comment by adamdecaf** [comment]
Is this when `0x20` is a byte (typically in `ImageData`) and it's treated as `\n` by the parser?

**Comment by ryanmwetzel** [comment]
Actually it is 0x0A of LF following each record type. 0x20 is a space in
ASCII and in image data and throughout the file.

**Comment by adamdecaf** [comment]
@ryanmwetzel Have you worked around this or patched the ICL library by chance?

**Comment by ryanmwetzel** [comment]
I am manually removing the LF currently. We can attempt to patch the code.

**Comment by ryanmwetzel** [comment]
Corrected with recent release.
