### ISSUE TITLE
reader: configure default readerOpts to honor Inserted Length Field

### ISSUE THREAD

**Issue by atonks2** [moov-io/imagecashletter#128]
**What were you trying to do?**
Call the create endpoint to read in an x9 binary file where each record begins with the requisite Inserted Length Field

**What did you expect to see?**
A successful file read

**What did you see?**
A `FileError` with unknown record type. The reader attempted to parse the length field as a record type.

**How can we reproduce the problem?**
Call the create file endpoint with a file containing length fields.

See also: https://github.com/moov-io/imagecashletter/pull/124#discussion_r514402471

**Comment by adamdecaf** [comment]
@atonks2 are you working on this?

**Comment by atonks2** [comment]
Yeah. Just working on some test updates.
