### ISSUE TITLE
Loose enforcement on mandatory fields when parsing an incoming files from external vendors.

### ISSUE THREAD

**Issue by SaraAdineh** [moov-io/imagecashletter#210]
**What were you trying to do?**
I'm trying to parse and open incoming return X9 files from our banking partner.

**What did you expect to see?**
I would like to be to get the parsed version of the file eventhough some of the required/mandatory fields are not provided.

**What did you see?**
I see the following error when trying to parse the file:
```record:ReturnDetailAddendumD *imagecashletter.FieldError EndorsingBankItemSequenceNumber is a mandatory field and has a default value, did you use ReturnDetailAddendumD()?```

**How can we reproduce the problem?**
This occurs on a lot of the mandatory fields. I'm wondering if for opening/parsing purposes, these mandates can be loose but for generating these files, we enforce them.

**Comment by atonks2** [comment]
Thanks for documenting this @SaraAdineh. I think your suggestion makes sense, but want to double check some specs. It seems like more flexible validation would be very helpful in this project. Something configurable... I'm not sure how I'd go about implementing it off the top of my head though.

**Comment by adamdecaf** [comment]
We solved this in the ACH library by including a [`ValidateOpts` struct with readers/writers](https://github.com/moov-io/ach/blob/master/file.go#L577) that can help configure this type of behavior.  Then [enforcement of required fields/values](https://github.com/moov-io/ach/blob/master/batchHeader.go#L257-L263) can check the struct. This field-level option also allows vendors who break the spec to still be parsable. 

I know X9 has a lot of specifications so we could wrap sets of these into an enum, but that seems like a future optimization.

**Comment by atonks2** [comment]
Thanks @adamdecaf! Yesterday I was trying to think through how to make this configurable. I didn't realize we'd already come up with a pattern in other services.
