### ISSUE TITLE
cannot read generated icl file using node fs

### ISSUE THREAD

**Issue by empoyoyoy** [moov-io/imagecashletter#227]
Hi, i am trying to save the response of GET /files/{fileID}/contents to an icl file please see details below:
  
<img width="696" alt="image" src="https://user-images.githubusercontent.com/25274538/158479573-7d4f4873-9dc6-496b-ac2b-9be176e9eb37.png">

in saving to an icl file i use fs library from node

i can create a icl file using fs please see created file below:

[T_20220316_053_nnnnnnnnnn0.txt](https://github.com/moov-io/imagecashletter/files/8257505/T_20220316_053_nnnnnnnnnn0.txt)

but when i try to upload the generated file in https://oss.moov.io/x9/
this is the issue i encounter
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/25274538/158480079-db34a7ca-4e9d-4b93-9514-08e3b7939772.png">

but when i try to save the same response using postman there were no issues encountered in uploading to https://oss.moov.io/x9/ the generated file via postman please see details below:
postman response:
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/25274538/158480617-a132faa9-d11d-4ae6-bbe1-b2b4baf14efd.png">

saved postman response file:
[postmanresponseicl.txt](https://github.com/moov-io/imagecashletter/files/8257539/postmanresponseicl.txt)

https://oss.moov.io/x9/ result:
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/25274538/158480824-aefedaef-c3f2-49fe-9144-1bd75bcc1143.png">

node version: v12.18.3

hoping that someone can help me with this issue

thank you :)

**Comment by adamdecaf** [comment]
@empoyoyoy it looks like node is encoding the response contents somehow. Are you aware of node doing that?

**Comment by empoyoyoy** [comment]
@adamdecaf yes  the problem is in node encoding, i solved this issue by using node exec command and curl
exec(`curl ${moovUri}/${iclId}/contents -o "${fileName}"`);

thank you for your answer :)
