### ISSUE TITLE
CreditItem problems for RecordType 61

### ISSUE THREAD

**Issue by dfproffesional** [moov-io/imagecashletter#243]
**What were you trying to do?**

I try to generate the ICL with record type 61 but it is not generated. 
The structure I need is this:

![image](https://user-images.githubusercontent.com/53260621/180359522-a00cbf42-e6c0-4ae3-9232-58fc42bbd3b0.png)

**What did you expect to see?**

I need a Binary x937 with Record Type 61 

![image](https://user-images.githubusercontent.com/53260621/180359586-b911a444-2fca-49d2-a23f-d2e0c39f60be.png)

**What did you see?**
I see the record type 62 but I need 61 for to specific vendor. 

**How can we reproduce the problem?**
This is generated by trying to use record type 61.

**Comment by atonks2** [comment]
Thanks for the detail @dfproffesional. 

I was able to locate [another PDF](https://www.bidnet.com/bneattachments?/529295290.pdf) that defines a format for record type 61, but it differs from the fields you've shown above. I see mention of Citi in your screenshot, and the PDF I found was produced by U.S. Bank. It would seem this record is defined differently by different institutions.

I'm concerned that we'll end up implementing a format that only works for one vendor or use-case. Are you ware of a more generalized format, or is record type 61 always specific to the vendor?

**Comment by dfproffesional** [comment]
Yes, the format is record type 61. And that PDF can be used for us.

**Comment by atonks2** [comment]
It would appear the document I linked to in [my earlier comment](https://github.com/moov-io/imagecashletter/issues/243#issuecomment-1192867252) has been taken down, so the link now returns 404. Luckily I have a local copy of it :) 

[529295290.pdf](https://github.com/moov-io/imagecashletter/files/9200242/529295290.pdf)

**Comment by dfproffesional** [comment]
Oh! Thank you! I'll be waiting for testing.
