### ISSUE TITLE
Failed to push the docker image to Cloud Foundry

### ISSUE THREAD

**Issue by krisho007** [moov-io/imagecashletter#301]
I am having an issue when I deploy the Docker image to cloud foundry (provided by [SAP BTP](https://help.sap.com/docs/btp/sap-business-technology-platform/development-in-cloud-foundry-environment))

**What were you trying to do?**
In the terminal, I executed the following command.
`cf push x9-moov --docker-image moov/imagecashletter:latest`

**What did you expect to see?**
I expected it to deploy the server and start.

**What did you see?**
The app was deployed, but it could not be started.
Here is the error log.
![image](https://github.com/moov-io/imagecashletter/assets/6290790/1d2056a7-389e-4acb-aade-ff1921109c1c)

I increased the timeout to 3 minutes and still time out for the health checkup. Any thoughts on how can I solve this issue?

**How can we reproduce the problem?**
SAP BTP provides a trial account with a Cloud Foundry environment.

**Comment by adamdecaf** [comment]
Do you have the output that's easier to read? Red on blue is quite hard, but it looks like the ports for health checks are wrong?

**Comment by krisho007** [comment]
Got it fixed. The issue was with the health check port. By default, the Cloud Foundry checked on the 8080 port with no path. Had to make it to ping 8083 and the '/ping' path.
