### ISSUE TITLE
Does the API support image binary data to be included in the file?

### ISSUE THREAD

**Issue by pedroassumpcao** [moov-io/imagecashletter#86]
The ICL file examples don't contain the check image data for front and back. Does the API support that in case I need to include them as part of the final ICL generated file?

Thanks

**Comment by adamdecaf** [comment]
Are you asking about `ImageViewData`? That has `ImageData` which contains the image itself. 

https://godoc.org/github.com/moov-io/imagecashletter#ImageViewData

**Comment by adamdecaf** [comment]
This is accepted as escaped bytes, but we'll attempt to decode it as base64 data as well. See https://github.com/moov-io/imagecashletter/issues/100
